language: java
jdk: oraclejdk8
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn clean package
deploy:
  provider: heroku
  app: ms-sales-order-service
  skip_cleanup: true
  api_key:
    secure: WR3rODWLEkYqgjfqnsHjqz4fgWVfzL2CosvBv4v6yib0BRQoMiAtuJ+2uga/l0cclhrNrBsnKewlH7WOHMGsikBb1Tcaarm81QYW9fYJLTEbtAj0aHoqiQGXtFKjki7fgicSeMc7pa4a/eTpa4c3GagIsCSLVQoBqO2AAFyYFEduP+kECUaR162Gh7mwuHv8e0JiV/tT2a5MLacy6dfkUVBzbmOhbn4+YFeWTpq0ckHFOtM4C6/vroWyQpYjdPr2cA1rOsa8QqsmI18nMDruEuS9m0Swo3iLWir0f8f+WTJYczrC217a5PROYaRYeEsj8FjPUN8V7c+0n5v+wB8o6X+nxgWGfgXirQxTUdnrViq9VRBSFX3M4i75zh26enVCIGZb9CoQ4VKF/C14ptjBk88cUMZD1397HSTJ1HqHCenU3ZzjhYo49qlcZydUURi2/jX8Zco3T2HmtwqH0FLzVNpNibIxzssnir7XJZqLRc4CSCgRQC0Xct+3mlpNWSKioaMoc2KPanftEZ+1Z7eIM/2op0UKVHPi4AslCl0gplwmVABLgZJ4E/53zazPCUYTMB0p42mI8q6NusetmPs0vGbUyc/D9n9pUTsI/bhFYy4N9LQGCnBe1FzlFG88cqJwkV2z2/6F/YX/7XEyNNRP93MFXcC5GIC1OGBOzL+tvyA=
