language: java
jdk: oraclejdk8
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn clean package
deploy:
  provider: heroku
  app: ms-sales-order-service
  skip_cleanup: true
  api_key:
    secure: "QMGY/+FXFzpizrVgs2m3ItaAeTRa3N1zYtQsdUp3TPjg1Bc6WjTEy8+l5pyA3IItBTOKSQvJDr+N+DFdMaa/rTQoIQd2qjktt62cbUfO7rxIFbeYai9qUTlbt4+OgHqKlu62o4hkv8xpvm0oGnCCoGc1NGm/f7UjrYQjz/lViBO8rVTxP4ILN9Ncr6diB2CeCxz+pTGflMJ036s95H1HlgsoutVgt0okD0ywrRLXXczLi9LKVDGZzbCXxokRYt3Rog8idX5z+VJp7YykHdgGgObi4OGkMJEAlBirx2rtYYoWC8ULfa3zemDVqHSshcOfTDKOCHNN1ducJG3MjdY4qxxbXg/hu/N2CAvqjn2i250kpP057sGelsc29yfuf80T5MJwvYuzQlbyP6MxTa/DRepgVpcIsS7+Rr9TOLmwLEkLhLq9SxyHkZ96jDZK9fCLr4QFQsWNZJkKQfOzsvDU8mTIjIvcUjKa+y0D1dYGnF7yEtN4c3YZ3AAU0J6BWsatlCXKx3aJIzUsryrHpWrkP6DHzyxzpzwT7mVzrih6v1Lf06tHi5IuF1BA9jhrTW0/u0Sawnb24NQSXIbn49DsaY7JxNb0vTcxHRMy/E9RHGQO6Q1K7ABHhcNTkykplafibRfu1X1K+tePsf0tkA+F569sYAMayLGWxZTS6LE6GZQ="
