language: java
jdk: oraclejdk8
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn clean package
deploy:
  provider: heroku
  app: ms-sales-order-service
  skip_cleanup: true
  app_key:
    secure: QIKsZ5ePXqdeVY5x3gKOQ1+IcK7wQdvOTqA+RG4H42VN/3zgE17hz+RH33JpGkCeBjydi1GHPxxCawk9Bw1tsyM3TKPy9sLc35xcLYNxyAra95z6uXzEJz2cCPOaAMQ477ltxzmAuthPtqmPC3Q02mArYTg6t0LIrcNUfvVQxko/QXggDafY2npm42d58/KXlaD/R4FuXDlFK/6xzs9/d9qzjDNF/zgELN5XnuuF6Hx0rITQc/AaE+L92Syn/7REtFX63Y/0xlt7/bUj+s7Qulz2eaAFX2oHf16Ak3xupnSyT+37SgV7Qb7gOBgoi0UppSO/X9RopR2fgV99S9pfbVfUascc44FdUE6VVdvkKXTVuN4t9Dn4pNVjNZAx4k/m5c+0xThf4tO+tZgmPVCqvgvsA/Ij3gkDOnCH/RVQodBH7cRLOE56y2jCo618OJyga9NIHFgaixcYBYRUy+JHa4HiVzwCqMMDfyu08JTAg3uRq9zJa7wuIvxDl3mJO8GaYE7leyg3LL3rGXg0vpnP0nsErVuaJZU8geO86S6FS/4+zEirRodxW1ekpzIxEQLvqNRx/95W7ENVMG+UkibvIxGYMk4dvD3fuC3qWz9iY1semXfF4b8xd620fP4kUFUTxTpHtvSq8bsrjrWkJ7SnPgYe0duPPAIlfVUf45KZ+SI=
