language: java
jdk: oraclejdk8
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn clean package
deploy:
  provider: heroku
  app: ms-sales-order-service
  skip_cleanup: true
  api_key:
    secure: FrvqZZcG8emQW/8IJwK3ZNL+EFWHgK3krGSlmy2b1yUnPqNDo7UXtyKS2KUNF7Vdq9iiYJToJqyA5OSeu7amWxTue977QD/xqfB7tOMyIbEU0VyUkOWpRy8ACGDfaBSdXT1KeHoXiJHnEIFc2RW4KvnzKpKwy4Ohm6RjmkKrgYAn+HcXz+n/MLcEFkwfXMDqPGwNrAzUsbLf+uce2suxJUxpvWWeJB30JpGvGjfvlXj3mBZB9tNjHdt45t1NlTT12VivLUTGNVg462aB4Mxedl8VPbJhpyKc6jG29KrOpemRwcszJf7QxIHOkuB78/KTUgSjzb4lTdIWDrL9wHA7nIn8rDtXcPAWIGY98dv0lZxaszTb0E9EZvIgRjytFRHxxDDAY+TOSKb268dLJSn42ov+hN1wAfrsFwqcLchV3+elWKt0IKfIPGCmeCBHzpyJEDdY+5vDZcNNy6F/CCsN60BBX5iSbmZ14gjj0tJcofCHWb2DfCff94jLtr75bWNxWoHSyhdPK9BpsGk6VrzYbBTJQrFJNY1B7QaJofuD8AzvIv39a3aagn+zh4fIVv9KgyOwI5ZlqBH2b+CTb82rJbtiL1EzIwDnZeOZ5Q1mYvCG/f4l7PMrzbjaP6qDJUhx98Pnih+MhHd6jrmzP13zlKqRD1+QCPmqQ3G4eDhm2uo=
